### ISSUE TITLE
useWindowVirtualizer shows a blank area when there are multiple virtualizers on page

### ISSUE THREAD

**Issue by flowlyIL** [TanStack/virtual#417] opened 2022-11-05 08:10 UTC
### Describe the bug

Hello, thanks for your time!

One potential bug: when using multiple useWindowVirtualizers on a single page, I noticed that between each list there is a large blank area and only the last few items are shown on the bottom list.

A quick inspection suggests that the problem is `transform: translateY(${virtualRow.start}px)`  calculation doesn't reset between each useWindowVirtualizers instance (each list on the page). When I change the value of `translateY`  using the browser inspector and set it to 0 (or any other value based on the row height), the item is positioned correctly.

### Your minimal, reproducible example

https://codesandbox.io/s/wispy-fire-boq7ft?file=/src/App.tsx

### Steps to reproduce

scroll all the way to the bottom in the sandbox demo

### Expected behavior

The virtualized content should be able to handle multiple virtualized lists on the same page.

### Platform

macOS, Windows.

### tanstack-virtual version

v3.0.0-beta.18

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by piecyk** [comment] 2022-11-05 08:50
This would be fixed with https://github.com/TanStack/virtual/pull/409 Current list assumes that it starts from top and there is no other content.

**Comment by flowlyIL** [comment] 2022-11-06 15:09
@piecyk Thanks for your response!
I forked the package with the fix you mentioned and I'm trying to figure out EXACTLY what the `scrollMargin` value should be and how to calculate it.

For example here: https://codesandbox.io/s/throbbing-cloud-dy7sz4

Why does `2600` works?
Because it's the total height of the first list? 

Also, what is the error margin? (i.e. will 2800 work? 3000?)

thanks!

**Comment by piecyk** [comment] 2022-11-06 15:48
Hi @flowlyIL 

> Why does 2600 works?
Because it's the total height of the first list?

Yes, basic it's the height of elements before the list. I would say better is to read and observe position of the list with ResizeObserver, something like https://codesandbox.io/s/festive-tdd-0mslhl?file=/src/App.tsx

**Comment by piecyk** [comment] 2022-11-07 20:37
@flowlyIL should be fixed in latest beta

**Closed by piecyk** 2022-11-07 20:37 UTC

**Comment by flowlyIL** [comment] 2022-11-08 08:18
@piecyk Thanks.

**Comment by ISilviu** [comment] 2022-11-20 15:17
@piecyk the scroll margin is also added to the scroll functions exposed by the virtualizer. 
For example, if one would like to implement a "scroll to top" button for a window virtualized list, calling `virtualizer.scrollToOffset(0)` will move the scroll to the `(top + scrollMargin)` position. I would need it to take me to the top of the window, not the top of the list.

Example: https://codesandbox.io/s/jolly-voice-2210cf?file=/src/App.tsx

I didn't find a way to to disable this behavior and wrote an override for `scrollToFn`:
```js
scrollToFn: (offset, _, virtualizerInstance) => {
    virtualizerInstance.scrollElement.scrollTo({
        top: offset,
        behavior: 'smooth',
    });
},
```
Another way would be by calling the scroll function with a negative offset: `virtualizer.scrollToOffset(-scrollMargin)`.

However, a better way of handling this would be an extra option either at the virtualizer props or at the scroll functions arguments. What do you think?
Also, the `useWindowVirtualizer` hook can't be found in the docs.

I could also help with contributions, by the way.

**Comment by piecyk** [comment] 2022-11-20 15:36
Yes, that is true. I think it's expected behavior as you are in context of that virtualizer 

> However, a better way of handling this would be an extra option either at the virtualizer props or at the scroll functions arguments. What do you think?

Why not call `window.scrollTo`? if you are scrolling in the whole page not only the list?

**Comment by ISilviu** [comment] 2022-11-21 05:25
That's a good idea too, it's just that I would've liked to use the virtualizer's API.

**Comment by Yash-Mangal2** [comment] 2025-02-12 06:12
Add this it will work

` <div
              style={{
                height: `${rowVirtualizer.getTotalSize()}px`,
                width: "100%",
                position: "relative",
                contain: "strict",
              }}
            >`
