### ISSUE TITLE
NPM reports the latest package as 3.0.0-alpha.0

### ISSUE THREAD

**Issue by DigitalNaut** [TanStack/virtual#410] opened 2022-10-22 14:30 UTC
### Describe the bug

NPM lists a previous package on `npm outdated` and the [registry page](https://www.npmjs.com/package/@tanstack/react-virtual) as the latest but the current version is 3.0.0-beta.18

### Your minimal, reproducible example

N/A

### Steps to reproduce

1. Ran `npm outdated`
2. Confusion, despair and agony (kidding!)

### Expected behavior

Expected to see "3.0.0-beta.18" under the Latest column

### Platform

Windows

### tanstack-virtual version

3.0.0-beta.18

### Additional context

(None, just wanted to applaud your bug report form, it's so good)

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment] 2022-10-22 16:45
This is correct. It is still in beta. You can install the exact beta version you want to try

**Comment by DigitalNaut** [comment] 2022-10-22 17:02
Yep, I understand that. However, I think it'd make more sense to bump the npm version to the latest beta release since that includes all the recent bug fixes since June unless there are competing beta versions for the final release, but that doesn't seem to be the case. It also makes it easier to update & install dependencies via the native npm mechanism.

Just a minor suggestion. Many thanks.

**Comment by charkour** [comment] 2022-12-16 14:50
This is a duplicate of this https://github.com/TanStack/virtual/issues/380

**Closed** 2023-08-29 20:07 UTC
