### ISSUE TITLE
You have alpha version marked as latest on npm

### ISSUE THREAD

**Issue by ivan-palatov** [TanStack/virtual#606] opened 2023-10-12 02:54 UTC
### Describe the bug

This is not a software bug, but a logistics one. Sorry if I submit it to the wrong place. Currently, when someone tries to install `@tanstack/react-virtual` from npm, the version that gets installed (and is marked as latest) is [3.0.0-alpha.0](https://www.npmjs.com/package/@tanstack/react-virtual/v/3.0.0-alpha.0), but the current latest is [3.0.0-beta.65](https://www.npmjs.com/package/@tanstack/react-virtual/v/3.0.0-beta.65).

### Your minimal, reproducible example

run npm i @tanstack/react-virtual

### Steps to reproduce

1. Run `npm i @tanstack/react-virtual`
2. See that the version is [3.0.0-alpha.0](https://www.npmjs.com/package/@tanstack/react-virtual/v/3.0.0-alpha.0)

### Expected behavior

The version should either be 2.x or [3.0.0-beta.65](https://www.npmjs.com/package/@tanstack/react-virtual/v/3.0.0-beta.65)

### How often does this bug happen?

Every time

### Platform

- any operating system, any browser

### tanstack-virtual version

3.0.0-beta.65

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by wub** [comment] 2023-10-19 04:02
Duplicate of #380, which was closed with the following reason:
> We're releasing soon on main. Stay tuned.

That was on August 30, so take "soon" with a grain of salt.

**Comment by piecyk** [comment] 2023-10-19 13:13
Yes, we know, please bear with us and install latest version `[v3.0.0-beta.66](https://github.com/TanStack/virtual/releases/tag/v3.0.0-beta.66)` till we sort it out.

**Closed** 2023-12-28 02:53 UTC
